Add support for oathtool

diff --git a/core/makefile.in b/core/makefile.in
--- a/core/makefile.in
+++ b/core/makefile.in
@@ -36,6 +36,7 @@ LIBEVENT = libevent-2.1.12-stable
 MPFR = mpfr-4.1.0
 MUSL = musl-1.2.1
 NCURSES = ncurses-6.2
+OATH_TOOLKIT = oath-toolkit-2.6.7
 PCRE = pcre-8.44
 READLINE = readline-8.1
 RSYNC = rsync-3.1.3
@@ -95,6 +96,7 @@ BINARIES = \
 	$(LESS)/less \
 	$(LESS)/lessecho \
 	$(LESS)/lesskey \
+	$(OATH_TOOLKIT)/oathtool/oathtool \
 	$(RSYNC)/rsync \
 	$(SED)/sed/sed \
 	$(TMUX)/tmux \
@@ -121,6 +123,7 @@ FOLDER_CLEAN_TARGETS = \
 	clean-mpfr \
 	clean-musl \
 	clean-ncurses \
+	clean-oathtool \
 	clean-pcre \
 	clean-readline \
 	clean-rsync \
@@ -141,6 +144,7 @@ TAR_GZ_SIGNATURES = \
 	$(LIBEVENT).tar.gz.sig \
 	$(MUSL).tar.gz.sig \
 	$(NCURSES).tar.gz.sig \
+	$(OATH_TOOLKIT).tar.gz.sig \
 	$(PCRE).tar.gz.sig \
 	$(READLINE).tar.gz.sig \
 	$(RSYNC).tar.gz.sig \
@@ -918,6 +922,38 @@ $(BIN)/lessecho: $(LESS)/lessecho
 
 $(BIN)/lesskey: $(LESS)/lesskey
 	test -z "$(MAN)" || cp -f $?.nro $(MAN)/man1/$(@F).1
+	cp -f $? $@
+
+$(OATH_TOOLKIT).tar.gz $(OATH_TOOLKIT).tar.gz.sig:
+	$(WGET) -nc https://download.savannah.nongnu.org/releases/oath-toolkit/$@
+
+$(OATH_TOOLKIT)/Makefile: $(OATH_TOOLKIT)/.FOLDER
+	(cd $(@D); \
+	./configure \
+		CC="$(CC)" \
+		CFLAGS="$(CFLAGS)" \
+		LDFLAGS="$(LDFLAGS)" \
+		--disable-pam \
+		--disable-pskc \
+		--enable-static \
+		--prefix="$(PWD)/$(COMMON)" \
+	)
+
+# The "-all-static" option causes the configuration process to fail when
+# specified via LDFLAGS via "./configure" for reasons unknown to me. I am also
+# not sure why "-all-static" is needed period as this was cargo-culted from
+# https://github.com/jhswartz/static-builds/commit/cb5aaa2 without digging into
+# why it's required.
+$(OATH_TOOLKIT)/oathtool/oathtool: $(OATH_TOOLKIT)/Makefile
+	(cd $(@D)/../liboath && $(MAKE) -S)
+	(cd $(@D) && $(MAKE) LDFLAGS="$(LDFLAGS) -all-static" -S)
+
+oathtool: $(OATH_TOOLKIT)/oathtool/oathtool
+
+$(BIN)/oathtool: $(OATH_TOOLKIT)/oathtool/oathtool
+	if [ -n "$(MAN)" ]; then \
+		cp -f $(OATH_TOOLKIT)/oathtool/oathtool.1 $(MAN)/man1/; \
+	fi
 	cp -f $? $@
 
 $(RSYNC).tar.gz $(RSYNC).tar.gz.asc:
