Allow some expressions to be entered without space after "="
- (Ab)use Bash's command_not_found_handle feature to allow some
  arithmetic expressions to be entered with a space after "=". This
  unfortunately does not work when the expression contains a "/" that is
  not surrounded by spaces since the expression is interpreted as an
  absolute path by Bash.

diff --git a/configuration/bashrc b/configuration/bashrc
--- a/configuration/bashrc
+++ b/configuration/bashrc
@@ -228,6 +228,19 @@ function -define-aliases()
     export DECLARE_BASH_ALIASES
 }
 
+# Handler used to intercept arithmetic expressions so they can be entered
+# without having to add a space after the "=".
+#
+function command_not_found_handle()
+{
+    if [[ "$1" != =* ]]; then
+        printf "%s: command not found\n" "$1" >&2
+        return 127
+    fi
+
+    eval "= ${1#=} ${@:2}"
+}
+
 # Calculate the result of an expression. The result of the last successfully
 # evaluated expression as made available as the variable "x". The expression
 # must appear in the command history to be evaluated.
